### ISSUE TITLE
Inconsistency configuration controller package

### ISSUE THREAD

**Issue by MarkVink** [svenkubiak/mangooio#122]
I'm also using the Hibernate extension and I'm setting custom packages for controllers/jobs/models, my configuration looks like this;

```yaml
default:
    application:
        controller : my.custom.package.controllers.
    scheduler:
        package    : my.custom.package.jobs
    hibernate:
        models     : my.custom.package.models
```

As you can notice I have a dot only after the controller package; Bootstrap.java L171 concatenate the package and classMethod with each other. I think it would be nicer to have all package configuration without dot appended.
