### ISSUE TITLE
Master key is set in a config, but framework can't find it: "Failed to load masterkey file"

### ISSUE THREAD

**Issue by ismagilov** [svenkubiak/mangooio#289]
Output log:
> 10.04.2017 16:12:27,554 [main] ERROR io.mangoo.configuration.Config - Failed to load masterkey file. Please make sure to set a masterkey file if using encrypted config values
10.04.2017 16:12:27,556 [main] ERROR io.mangoo.configuration.Config - Found encrypted config value 'application.admin.username' but no masterkey was set.

```
dev:
    application:
        admin:
            enable: true
            username: cryptex[XnrslCZdmq9BW27skRxH5g==]
            password: $2a$12$dLSHOqKzDEt6tictTGbn8epV0kTEbiWpHx/VVRDoUVpFiS2bu6I6y 
            masterkey: /Users/ilya/Work/Projects/todobackend-mangooio/master.txt
```

Master key file is present on the filesystem:
> ilya$ cat /Users/ilya/Work/Projects/todobackend-mangooio/master.txt
sderokfoksm458349034rkwelkw34njk

If I am not mistaken, problem appeared after 4.3.2 upgrade.
